"""add confirm

Revision ID: e9673cbc0d46
Revises: None
Create Date: 2016-04-21 17:36:55.248021

"""

# revision identifiers, used by Alembic.
revision = 'e9673cbc0d46'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
